### ISSUE TITLE
Heatmap casos municipales Bolivia

### ISSUE THREAD

**Issue by dquintani** [pr0nstar/covid19-pruebas#1]
Muy buenas tardes estimado Sr. Arraya,

Estoy pensando si su gráfica en https://github.com/pr0nstar/covid19-pruebas/blob/master/img/casos.bolivia.heatmap.jpg podría ser mejorada de alguna forma. Me parece un poco raro que Santa Cruz de la SIerra, hoy el epicentro de la cuarta ola del COVID-19 en Bolivia, esté en la segunda mitad del ranking. Se entiende por qué ocurre esto (los casos de hoy son 1. relativamente bajos a comparación con olas anteriores y 2. la población relativamente grande del municipio), pero creo que si el objetivo es poner a los municipios con los rebrotes más significativos arriba, algo hay que cambiar.

Espero que entienda mi preocupación sobre el tema. Por ahora no puedo pensar en soluciones por flojeritis crónica.

De antemano le agradezco y espero que tenga un fantástico día. 

-Diego de BoliGráfica

**Comment by pr0nstar** [comment]
Tal vez algo asi sea mas la onda que estas buscando.

![casos activos joy division](https://user-images.githubusercontent.com/64463227/144539072-8fb0eb0d-5e8b-4cbe-b2c2-916a35639fba.jpg)

**Comment by dquintani** [comment]
poné en el reddit de joy division (sin texto) y dejate de joder   ( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿
